kind: pipeline
name: default
steps:
  - name: tags
    image: alpine/git
    commands:
      - echo -n "$(git rev-parse --short HEAD),latest" > .tags

  - name: build
    image: plugins/docker
    settings:
      repo: shrivara/shrivara-dev
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: deploy
    image: lachlanevenson/k8s-kubectl
    environment:
      KUBE_CONFIG:
        from_secret: kube_config
      DOCKER_USERNAME:
        from_secret: docker_username
    commands:
      - echo "${DOCKER_USERNAME}"
      - echo "$DOCKER_USERNAME"
      - echo "${KUBE_CONFIG}" > kubeconfig.yaml
      - kubectl --kubeconfig="kubeconfig.yaml" config get-contexts
      - head -n 3 kubeconfig.yaml
