kind: pipeline
name: default
steps:
  - name: tags
    image: alpine/git
    commands:
      - echo -n $(git rev-parse --short HEAD) > .short_tag
      - echo -n "$(cat .short_tag),latest" > .tags

  - name: build
    image: plugins/docker
    settings:
      repo: shrivara/shrivara-dev
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: deploy-stage
    image: lachlanevenson/k8s-kubectl
    environment:
      KUBE_CONFIG:
        from_secret: kube_config
    commands:
      - echo "$KUBE_CONFIG" > kubeconfig.yaml
      - kubectl --kubeconfig="kubeconfig.yaml" -n shrivara-dev-stage set image deployment/deployment shrivara-dev=shrivara/shrivara-dev:$(cat .short_tag)
