kind: pipeline
name: default

steps:
- name: website
  image: plugins/docker
  settings:
    repo: shrivara/shrivara-dev
    tags: latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
